party:
  nome-crianca: "Samuel"
  slug: "samuel-3-anos"
  idade: "3"
  data-festa: "14/11/2026"
  dia-semana: "SÁBADO"
  horario: "17h às 21h"
  local: "Salão de Festas — Condomínio Residencial Siena"
  endereco: "Águas Claras"
  link-google-maps: "https://maps.app.goo.gl/VsdHpbBB83hwMCYX6"
  mensagem-hero: "Venha fazer parte dessa aventura!"
  texto-apresentacao: "O amigável da vizinhança está fazendo 3 anos e conta com você nessa missão especial!"
  mensagem-faixa: "Prepare-se para uma mega aventura!"
  mensagem-presenca: "Contamos com sua presença!"
  mensagem-missao: "ACEITAR ESSA MISSÃO"
  whatsapp-number: "+351913154440"
  email-recepcao: "raquel90.menezes2@gmail.com"
  instagram-handle: "[INSTAGRAM]"
  caixa-18-anos:
    titulo: "🕷️ PROJETO: SAMUEL 18 ANOS"
    texto: |
      Hoje o nosso pequeno herói está completando 3 anos. Mas toda grande aventura tem um próximo capítulo!

      Se você não souber o que presentear, ou simplesmente quiser contribuir para a futura Caixinha dos 18 anos do Samuel, também temos essa opção.

      É opcional, viu? O mais importante é ter você com a gente nessa missão! ❤️
    qr-code-url: "/assets/images/qr-code-caixinha-18.png"
    pix-key: "+55 (61) 99262-8452"
